- name: Déployer le Hello World sur serveur
  hosts: webservers
  become: false
  tasks:
    - name: Créer le dossier
      file:
        path: ~/hello_world
        state: directory

    - name: Envoyer les fichiers du projet
      copy:
        src: .
        dest: ~/hello_world
        exclude: ['.git', '__pycache__']

    - name: Installer requirements Python
      pip:
        requirements: ~/hello_world/requirements.txt
